#include "Particle/ParticleEvent.h"
#include "Particle/ParticleSystemComponent.h"

AParticleEventManager::~AParticleEventManager()
{
	UnbindParticleSystemComponent();
}

// Function : Bind this manager as a runtime listener for a particle system component
// input : InComponent
// InComponent : component whose OnParticleCollide delegate should be forwarded by this manager
// output : Existing binding is replaced; no asset reference is serialized
void AParticleEventManager::BindToParticleSystemComponent(UParticleSystemComponent* InComponent)
{
	if (BoundComponent == InComponent)
	{
		return;
	}

	UnbindParticleSystemComponent();
	BoundComponent = InComponent;
	if (BoundComponent)
	{
		BoundCollisionDelegateId = BoundComponent->OnParticleCollide.Add(
			[this](const FParticleEventCollideData& EventData)
			{
				HandleParticleCollide(EventData);
			});
	}
}

// Function : Remove the runtime particle component listener
// input : None
// output : This manager no longer receives PSC collision delegate broadcasts
void AParticleEventManager::UnbindParticleSystemComponent()
{
	if (BoundComponent && BoundCollisionDelegateId != 0)
	{
		UObject* BoundObject = BoundComponent;
		if (UObjectManager::Get().ContainsObject(BoundObject) &&
			Cast<UParticleSystemComponent>(BoundObject) == BoundComponent)
		{
			BoundComponent->OnParticleCollide.Remove(BoundCollisionDelegateId);
		}
	}
	BoundComponent = nullptr;
	BoundCollisionDelegateId = 0;
}

// Function : Add particle collision event to manager queue
// input : EventData
// EventData : collision event data generated by a particle system component
// output : Collision event is stored until DispatchEvents is called
void AParticleEventManager::PushCollisionEvent(const FParticleEventCollideData& EventData)
{
	CollisionEvents.push_back(EventData);
}

// Function : Forward one PSC collision delegate event through this manager
// input : EventData
// EventData : collision event broadcast by UParticleSystemComponent
// output : EventData is queued, broadcast through OnParticleCollide, then cleared
void AParticleEventManager::HandleParticleCollide(const FParticleEventCollideData& EventData)
{
	PushCollisionEvent(EventData);
	DispatchEvents();
}

// Function : Queue a batch of particle collision events and broadcast them
// input : EventDataList
// EventDataList : collision events drained from a particle system component
// output : OnParticleCollide is broadcast for each event and the manager queue becomes empty
void AParticleEventManager::DispatchCollisionEvents(const TArray<FParticleEventCollideData>& EventDataList)
{
	for (const FParticleEventCollideData& EventData : EventDataList)
	{
		PushCollisionEvent(EventData);
	}
	DispatchEvents();
}

// Function : Broadcast queued particle collision events and clear the queue
// input : None
// output : OnParticleCollide is broadcast for each queued event and the queue becomes empty
void AParticleEventManager::DispatchEvents()
{
	for (const FParticleEventCollideData& EventData : CollisionEvents)
	{
		OnParticleCollide.Broadcast(EventData);
	}
	CollisionEvents.clear();
}

void AParticleEventManager::InitDefaultComponents()
{
	// Dispatcher only. Particle simulation remains owned by UParticleSystemComponent.
}
